### ISSUE TITLE
Docker Compose란?

### ISSUE THREAD

**Issue by hjgel** [hjgel/my-todo#36]
## Docker Compose
- 여러 개의 Docker 컨테이너들을 하나의 서비스로 정의하고 구성해 하나의 묶음으로 관리할 수 있게 도와주는 툴

### Docker Compose를 사용하는 이유
1. 여러 개의 컨테이너를 관리하는 데 용이
2. 복잡한 명령어로 실행시키던 Docker Cli를 간소화 시킬 수 있음. 

## 자주 사용하는 Docker Compose CLI 명령어
```
# compose.yml

services:
  webserver:
    container_name: webserver
    image: nginx
    ports:
      - 80:80
```

**컨테이너 실행**
```
docker compose up  # 포그라운드에서 실행
docker compose up -d # 백그라운드에서 실행
```

**Docker Compose로 실행시킨 컨테이너 확인**
```
# compose.yml에 정의된 컨테이너 중 실행 중인 컨테이너만 보여줌
docker compose ps

# compose.yml에 정의된 모든 컨테이너를 보여줌
docker compose ps -a
```

**Docker Compose 로그 확인**
```
# compose.yml에 정의된 모든 컨테이너의 로그를 모아서 출력
docker compose logs
```

**컨테이너를 실행하기 전에 재빌드하기**
```
docker compose up --build # 포그라운드에서 실행
docker compose up --build -d # 백그라운드에서 실행
```
compose.yml에서 정의한 이미지 파일에서 코드가 변경됐을 경우, 이미지를 다시 빌드해서 컨테이너를 실행시켜야 적용된다. 
그러므로 이럴 때는 --build 옵션을 추가해서 사용해야 한다. 

**이미지 다운받기 / 업데이트하기**
```
docker compose pull
```
compose.yml에서 정의된 이미지를 다운 받거나 업데이트 한다.

**Docker Compose에서 이용한 컨테이너 종료**
```
docker compose down
```
